from pydantic import BaseModel

class HouseInput(BaseModel):
    Suburb: str
    Type: str
    Method: str
    SellerG: str
    CouncilArea: str
    Regionname: str
    Rooms: float
    Distance: float
    Postcode: float
    Bedroom2: float
    Bathroom: float
    Car: float
    Landsize: float
    Lattitude: float
    Longtitude: float
    Propertycount: float
    SaleYear: float
    SaleMonth: float

class WicketInput(BaseModel):
    innings: float
    over: float
    ball_in_over: float
    batting_team: str
    bowling_team: str
    striker: str
    bowler: str
    cum_runs: float
    cum_wickets: float
    balls_bowled_in_innings: float
    balls_left: float
    wickets_left: float
    current_run_rate: float
    last_6_ball_runs: float
    last_6_ball_wickets: float

class WinProbabilityInput(BaseModel):
    over: float
    ball_in_over: float
    batting_team: str
    bowling_team: str
    cum_runs_2nd: float
    cum_wickets_2nd: float
    balls_bowled_2nd: float
    balls_left: float
    wickets_left: float
    target: float
    runs_required: float
    current_run_rate: float
    required_run_rate: float
    rrr_minus_crr: float
    last_6_runs: float
    last_6_wickets: float

class BatterClusterInput(BaseModel):
    total_runs: float
    balls_faced: float
    strike_rate: float
    boundary_pct: float
    avg_runs_per_ball: float